name: Reload Website Every 5 Minutes

on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  reload_website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run reload script
      run: python reload_website.py
